sonar.projectKey=dietly-scraper
sonar.projectName=dietly-scraper
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc,tests/**,venv/**,.venv/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3
