name: SonarQube Analysis

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  sonarqube:
    uses: gOOrcio/sonarqube-sandbox/.github/workflows/reusable-sonar-python.yml@1a1aedc42a80414ed7c5a9a84aab11c4ee55cafd
    with:
      project_key: dietly-scraper
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
